/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface AccessibilityFeature {
  id: Generated<number | null>;
  name: string;
}

export interface Account {
  avatar_url: Generated<string | null>;
  created_at: Generated<string | null>;
  deleted_at: Generated<string | null>;
  id: Generated<number | null>;
  pin_hash: string;
  role_id: number;
  updated_at: Generated<string | null>;
  username: string;
}

export interface AccountRole {
  id: Generated<number | null>;
  name: string;
}

export interface AccountSchedule {
  account_id: number;
  allow_end_min: number;
  allow_start_min: number;
  day_of_week: number;
  enabled: Generated<number>;
  id: Generated<number | null>;
  max_duration_min: number | null;
}

export interface BlockedEntity {
  account_id: number;
  entity_id: number;
  entity_type_id: number;
}

export interface Collection {
  account_id: number;
  created_at: Generated<string | null>;
  deleted_at: Generated<string | null>;
  description: Generated<string | null>;
  id: Generated<number | null>;
  name: string;
  updated_at: Generated<string | null>;
}

export interface Currency {
  code: string;
  id: Generated<number | null>;
  name: string;
  symbol: string;
}

export interface Developer {
  id: Generated<number | null>;
  name: string;
}

export interface Dlc {
  created_at: Generated<string | null>;
  deleted_at: Generated<string | null>;
  deleted_by: number | null;
  description: string | null;
  game_id: number;
  id: Generated<number | null>;
  is_owned: Generated<number | null>;
  release_date: string | null;
  size_bytes: number | null;
  title: string;
  updated_at: Generated<string | null>;
  updated_by: number | null;
}

export interface EntityType {
  id: Generated<number | null>;
  name: string;
}

export interface Feature {
  id: Generated<number | null>;
  name: string;
}

export interface Franchise {
  created_at: Generated<string | null>;
  created_by: number | null;
  deleted_at: Generated<string | null>;
  deleted_by: number | null;
  id: Generated<number | null>;
  name: string;
  updated_at: Generated<string | null>;
  updated_by: number | null;
}

export interface Game {
  created_at: Generated<string | null>;
  deleted_at: Generated<string | null>;
  deleted_by: number | null;
  description: string | null;
  hltb_completionist_min: number | null;
  hltb_main_extra_min: number | null;
  hltb_main_min: number | null;
  id: Generated<number | null>;
  is_owned: Generated<number | null>;
  max_players: number | null;
  min_players: number | null;
  release_date: string | null;
  release_status: string | null;
  size_bytes: number | null;
  title: string;
  updated_at: Generated<string | null>;
  updated_by: number | null;
  version: string | null;
}

export interface GameAccessibilityFeature {
  accessibility_feature_id: number;
  game_id: number;
}

export interface GameAchievement {
  description: string | null;
  game_id: number;
  id: Generated<number | null>;
  name: string;
  progress_current: Generated<number | null>;
  progress_total: Generated<number | null>;
  rarity: number | null;
  secret: Generated<number | null>;
  unlocked_at: string | null;
}

export interface GameCollection {
  collection_id: number;
  game_id: number;
}

export interface GameDeveloper {
  developer_id: number;
  game_id: number;
}

export interface GameEdition {
  edition: string;
  game_id: number;
  id: Generated<number | null>;
}

export interface Genre {
  id: Generated<number | null>;
  name: string;
}

export interface Library {
  code: string;
  id: Generated<number | null>;
  name: string;
}

export interface Locale {
  code: string;
  id: Generated<number | null>;
  name: string;
}

export interface MediaType {
  id: Generated<number | null>;
  name: string;
}

export interface Migrations {
  applied_at: Generated<string | null>;
  name: string | null;
}

export interface Platform {
  code: string;
  id: Generated<number | null>;
  name: string;
}

export interface Publisher {
  id: Generated<number | null>;
  name: string;
}

export interface Rating {
  id: Generated<number | null>;
  min_age: number;
  name: string;
  source_id: number;
}

export interface RatingDescriptor {
  descriptor: string;
  id: Generated<number | null>;
  source_id: number;
}

export interface RatingSource {
  id: Generated<number | null>;
  name: string;
}

export interface Region {
  code: string;
  id: Generated<number | null>;
  name: string;
}

export interface ScoreSource {
  id: Generated<number | null>;
  name: string;
}

export interface Series {
  created_at: Generated<string | null>;
  created_by: number | null;
  deleted_at: Generated<string | null>;
  deleted_by: number | null;
  id: Generated<number | null>;
  name: string;
  updated_at: Generated<string | null>;
  updated_by: number | null;
}

export interface Status {
  id: Generated<number | null>;
  name: string;
}

export interface Tag {
  id: Generated<number | null>;
  name: string;
}

export interface DB {
  accessibility_feature: AccessibilityFeature;
  account: Account;
  account_role: AccountRole;
  account_schedule: AccountSchedule;
  blocked_entity: BlockedEntity;
  collection: Collection;
  currency: Currency;
  developer: Developer;
  dlc: Dlc;
  entity_type: EntityType;
  feature: Feature;
  franchise: Franchise;
  game: Game;
  game_accessibility_feature: GameAccessibilityFeature;
  game_achievement: GameAchievement;
  game_collection: GameCollection;
  game_developer: GameDeveloper;
  game_edition: GameEdition;
  genre: Genre;
  library: Library;
  locale: Locale;
  media_type: MediaType;
  migrations: Migrations;
  platform: Platform;
  publisher: Publisher;
  rating: Rating;
  rating_descriptor: RatingDescriptor;
  rating_source: RatingSource;
  region: Region;
  score_source: ScoreSource;
  series: Series;
  status: Status;
  tag: Tag;
}
